---
- name: Deploy WireGuard configuration
  hosts: all
  become: true  # Run specific tasks as root
  tasks:

    - name: Install WireGuard package
      package:
        name: wireguard
        state: present
      become: true

    - name: Copy WireGuard config file (Only if changed)
      copy:
        src: "wg0.conf/{{ inventory_hostname.split('.')[0] }}.conf"
        dest: "/etc/wireguard/wg0.conf"
        owner: root
        group: root
        mode: "0600"
      become: true
      notify: Restart WireGuard

    - name: Ensure IPv4 forwarding is enabled in /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv4.ip_forward = 1"
        state: present
      become: true
      notify: Apply sysctl changes

  handlers:
    - name: Apply sysctl changes
      command: sysctl -p
      become: true

    - name: Restart WireGuard
      systemd:
        name: "wg-quick@wg0"
        state: restarted
        enabled: true
      become: true

